Jenkins caf module
aztfmod/terraform-addons-caf pull request #8
Opened 2021-05-05 20:11 UTC by kavithai

2021-05-05 20:16 UTC, hattan commented on modules/jenkins/README.md
> +# GitLab CAF Module
Shouldn't this be the Jenkins CAF Module?

2021-05-05 20:17 UTC, hattan requested changes
Looks great, just two small doc changes to replace references to gitlab with jenkins

2021-05-05 20:17 UTC, hattan commented on modules/jenkins/README.md
> +This submodule is part of [Cloud Adoption Framework](https://github.com/aztfmod/terraform-azurerm-caf) landing zones for [GitLab on Terraform](https://github.com/taiidani/terraform-provider-jenkins).
There is another reference to gitlab in the link text

2021-05-05 20:17 UTC, hattan commented on modules/jenkins/project.tf
> +  count              = (var.job.folderName!="" && var.job.createFolder=="true")? "1":"0"
👍 very cool!

2021-05-05 20:20 UTC, hattan commented
Due to the current architecture, we need to include the JENKINS variables in the other ci workflows like this
https://github.com/aztfmod/terraform-addons-caf/blob/jenkinsCafModule/.github/workflows/ci_gitlab.yml#L105

When the refactor to break them apart takes place we can then remove the need for these.

2021-05-11 18:53 UTC, in4margaret commented on .github/workflows/ci_jenkins.yml
> +          # deploy jenkins
Please specify what exactly get deployed

2021-05-11 18:53 UTC, in4margaret commented on modules/jenkins/variables.tf
> +  description = "The object representative of the gitlab project entity to update"
github -> jenkins?

2021-05-11 19:02 UTC, in4margaret requested changes

2021-05-11 19:02 UTC, in4margaret commented on .github/workflows/ci_jenkins.yml
> +          # destroy launchpad
Can you run destroy even when previous steps errored out?

2021-06-21 16:47 UTC, DariuszPorowski commented
I am going to close this PR, because this module has been adjusted to new structure and published under this PR: https://github.com/aztfmod/terraform-addons-caf/pull/13

2021-06-21 16:47 UTC, closed without merging